IanVS/prettier-plugin-sort-imports

src/preprocessor.ts, src/utils/__tests__/get-code-from-ast.spec.ts, src/utils/__tests__/remove-nodes-from-original-code.spec.ts, src/utils/get-all-comments-from-nodes.ts, src/utils/get-code-from-ast.ts, src/utils/get-import-nodes.ts, src/utils/get-sorted-nodes.ts, src/utils/remove-nodes-from-original-code.ts, tests/PreserveStrict/__snapshots__/ppsi.spec.js.snap, tests/PreserveStrict/comments-on-directive-are-preserved.ts, tests/PreserveStrict/custom-directive-remains-at-top.ts, tests/PreserveStrict/multiple-directives-remain-at-top.ts, tests/PreserveStrict/ppsi.spec.js, tests/PreserveStrict/strict-directive-remains-at-top.ts, tests/PreserveStrict/string-literal-at-top-is-pushed-down.ts, tests/RemoveStatementsFromOriginalCode/__snapshots__/ppsi.spec.js.snap, tests/RemoveStatementsFromOriginalCode/does-not-remove-content-in-string-literal.ts, tests/RemoveStatementsFromOriginalCode/does-remove-import-after-inline-comment.ts, tests/RemoveStatementsFromOriginalCode/ppsi.spec.js
This fixes #5 and also includes the fix for #7 since I need it for this.  While the relevance of strict directives may be doubtful for modules, correctness is still a goal and we should still preserve the original code and only order imports. 
For references, this code
```javascript
// below is a directive prologue
'use custom' ; /* more directives... */ 'enable typecheck'
'forbid IE'
import './SetupEnvironment';
import type { Period } from './Period'
"this is not a directive prologue";
function foo() {
}
```
now becomes
```javascript
// below is a directive prologue
"use custom";
/* more directives... */
"enable typecheck";
"forbid IE";
import "./SetupEnvironment";
import type { Period } from "./Period";
("this is not a directive prologue");
function foo() {}
```
and the following …
=> Preserve directive prologues fixes #5 #7

README.md, src/constants.ts, src/preprocessor.ts, src/types.ts, src/utils/__tests__/get-all-comments-from-nodes.spec.ts, src/utils/__tests__/get-code-from-ast.spec.ts, src/utils/__tests__/get-import-nodes-matched-group.spec.ts, src/utils/__tests__/get-sorted-nodes-by-import-order.spec.ts, src/utils/__tests__/get-sorted-nodes.spec.ts, src/utils/__tests__/remove-nodes-from-original-code.spec.ts, src/utils/get-sorted-nodes-by-import-order.ts
This is a cherry-pick of a PR from @nickhudkins to the upstream project: https://github.com/trivago/prettier-plugin-sort-imports/pull/150, adjusted slightly to work within the rule of this project to not sort beyond side-effect import groups.  
@blutorange what do you think of this?  I'm reluctant to add another option, but if we changed this without an option it would be a breaking change.  I don't have a strong opinion one way or the other, but personally I do like sorting builtins to the top, so it would be nice to have some way to do it.
=> Introduce `importOrderBuiltinModulesToTop` for Node Builtins

README.md, src/utils/__tests__/adjust-comments-on-sorted-nodes.spec.ts, src/utils/__tests__/get-sorted-nodes-by-import-order.spec.ts, src/utils/__tests__/get-sorted-nodes.spec.ts, src/utils/adjust-comments-on-sorted-nodes.ts, src/utils/get-sorted-nodes-by-import-order.ts, src/utils/get-sorted-nodes-names-and-newlines.ts, src/utils/get-sorted-nodes-names.ts, src/utils/get-sorted-nodes.ts, test-setup/run_spec.js, tests/ImportsSeparatedByEmptyRegex/__snapshots__/ppsi.spec.js.snap, tests/ImportsSeparatedByEmptyRegex/import-export-in-between.ts, tests/ImportsSeparatedByEmptyRegex/import-export-only.ts, tests/ImportsSeparatedByEmptyRegex/imports-with-comments-and-third-party.ts, tests/ImportsSeparatedByEmptyRegex/imports-with-comments-on-top.ts, tests/ImportsSeparatedByEmptyRegex/imports-with-comments.ts, tests/ImportsSeparatedByEmptyRegex/imports-with-file-level-comments.ts, tests/ImportsSeparatedByEmptyRegex/imports-without-third-party.ts, tests/ImportsSeparatedByEmptyRegex/no-import-export.ts, tests/ImportsSeparatedByEmptyRegex/one-import.ts, tests/ImportsSeparatedByEmptyRegex/ppsi.spec.js
Closes #11
This is an adaptation of https://github.com/trivago/prettier-plugin-sort-imports/pull/42 from @atombrenner.  I wasn't able to use most of the commits from the original branch, because our approach is different in this project, but I did pull in his commit with tests.  
The other change I needed to make here was to modify the cloned nodes in `adjustCommentsOnSortedNodes`, rather than mutating the original, which was leading to some strange bugs in the tests.
=> Custom import order separation

src/index.ts
I pulled release 3.4.0 and added the new rule, and unfortunately got these complaints from prettier:
```
[warn] Ignored unknown option { importOrderBuiltinModulesToTop: true }.
```
I compared other Config Options, and this is my guess at the necessary fix
=> Fix: "Ignore unknown option importOrderBuiltinModulesToTop"

src/utils/get-sorted-nodes-by-import-order.ts, tests/ImportsSeparatedByEmptyRegex/__snapshots__/ppsi.spec.js.snap
I think this screenshot will highlight what I feel like an inconsistency:
=> Avoid initial new line when using custom group separator

README.md, docs/TROUBLESHOOTING.md, src/constants.ts, src/index.ts, src/preprocessor.ts, src/types.ts, src/utils/__tests__/get-all-comments-from-nodes.spec.ts, src/utils/__tests__/get-code-from-ast.spec.ts, src/utils/__tests__/get-import-flavor-of-node.spec.ts, src/utils/__tests__/get-sorted-nodes-by-import-order.spec.ts, src/utils/__tests__/get-sorted-nodes.spec.ts, src/utils/__tests__/merge-nodes-with-matching-flavors.spec.ts, src/utils/__tests__/remove-nodes-from-original-code.spec.ts, src/utils/get-chunk-type-of-node.ts, src/utils/get-code-from-ast.ts, src/utils/get-import-flavor-of-node.ts, src/utils/get-sorted-nodes.ts, src/utils/has-ignore-next-node.ts, src/utils/merge-nodes-with-matching-flavors.ts
This PR implements import declaration merging for duplicate imports.
- I had to adjust `getCodeFromAST` so that we could still provide the original nodes, even if some of the nodes were being deleted.
- It leverages the existing chunking logic, so if there's a `side-effect` import, or a `prettier-ignore` import, it won't merge across that boundary.
- I did not implement conversion of `import type { stuff }` into `import { type stuff }` as it was not obvious when this would be wise. If we want to control that with an additional config option, something like `importOrderMergeTypeStyle: "none" | "to-normal-import" | "unmerge"` I could be convinced. I forsee people wanting opposite sides of the coin for that one.
Please let me know what you think and if there's any edge-cases I missed!
=> Feature: `importOrderMergeDuplicateImports`

src/utils/get-sorted-nodes-by-import-order.ts
I think another lodash import was added after refactoring to use more fine-grained lodash import in https://github.com/IanVS/prettier-plugin-sort-imports/pull/21
=> Fix: broken lodash import

README.md, package.json, src/types.ts, types/index.d.ts
Ported from https://github.com/trivago/prettier-plugin-sort-imports/pull/173 & https://github.com/trivago/prettier-plugin-sort-imports/pull/180
We'll likely be deprecating many of these options in the future, but for now, we may as well expose their types and give them some nice docs.
=> Expose types for config options

README.md, docs/TROUBLESHOOTING.md, package.json, src/preprocessors/vue.ts, yarn.lock
Addresses @fbartho's suggestion in https://github.com/IanVS/prettier-plugin-sort-imports/pull/40#discussion_r1005911669.
Adapted from https://github.com/trivago/prettier-plugin-sort-imports/pull/183
=> Make vue dependency optional

README.md, src/constants.ts, src/preprocessors/preprocessor.ts, src/types.ts, src/utils/__tests__/explode-type-and-value-specifiers.spec.ts, src/utils/explode-type-and-value-specifiers.ts, src/utils/get-import-nodes-matched-group.ts, src/utils/get-sorted-nodes.ts, tests/TypesSpecialWord/__snapshots__/ppsi.spec.js.snap, tests/TypesSpecialWord/imports-with-mixed-declarations.ts, tests/TypesSpecialWord/imports-with-third-party-types.ts, tests/TypesSpecialWord/ppsi.spec.js, types/index.d.ts
Closes https://github.com/IanVS/prettier-plugin-sort-imports/issues/35
Adapted from https://github.com/trivago/prettier-plugin-sort-imports/pull/153, by @Xenfo.  
This adds a new special string, `<TYPES>` that can be added to the `importOrder` array.  When used, it will cause type imports to be sorted as specified by its location in the array.  
Notes:
- If it is used, it will disable `importOrderCombineTypeAndValueImports`, throwing a warning if both are used.  This is because:
- We will split apart type and value import declarations if `<TYPES>` is used, so that types can be sorted appropriately.  
- Thinking towards the next breaking change when we remove options, I think the default will be to enable `importOrderCombineTypeAndValueImports`, and this change will give users a good way …
=> Support explicit type sorting

src/utils/__tests__/get-import-nodes-matched-group.spec.ts, src/utils/get-import-nodes-matched-group.ts, tests/TypesSpecialWord/__snapshots__/ppsi.spec.js.snap, tests/TypesSpecialWord/imports-with-mixed-declarations.ts, tests/TypesSpecialWord/ppsi.spec.js
We had a bug, identified by @mattiaz9 in https://github.com/IanVS/prettier-plugin-sort-imports/issues/35#issuecomment-1293903705, which was causing the `"^[./]"` group to include both type and value imports, instead of only value imports.
This PR fixes that bug, and expands both the unit and e2e tests, which fail without this change and pass with it.
=> Fix type/non-type sorting

README.md, src/constants.ts, src/index.ts, src/preprocessors/preprocessor.ts, src/types.ts, src/utils/__tests__/get-all-comments-from-nodes.spec.ts, src/utils/__tests__/get-code-from-ast.spec.ts, src/utils/__tests__/get-sorted-nodes-by-import-order.spec.ts, src/utils/__tests__/get-sorted-nodes.spec.ts, src/utils/__tests__/merge-nodes-with-matching-flavors.spec.ts, src/utils/__tests__/remove-nodes-from-original-code.spec.ts, src/utils/get-sorted-nodes-by-import-order.ts, src/utils/merge-nodes-with-matching-flavors.ts, test-setup/run_spec.ts, tests/ImportOrderBuiltinModulesToTop/ppsi.spec.ts, types/index.d.ts
Reference: #22 
This is the first step towards removing some options from this plugin, to make it a bit more opinionated and easy to configure (and maintain). 
This PR removes the option for `importOrderBuiltinModulesToTop`, and instead sorts builtins to the top always.
We could potentially add a special flag for use in `importOrder` if someone wants to control the order of where the builtins appear, but I'd like to avoid doing that unless it becomes necessary.
=> [Breaking] Remove importOrderBuiltinModulesToTop (always true)

README.md, docs/MIGRATION.md, src/index.ts, src/preprocessors/preprocessor.ts, src/types.ts, src/utils/__tests__/get-all-comments-from-nodes.spec.ts, src/utils/__tests__/get-code-from-ast.spec.ts, src/utils/__tests__/get-sorted-nodes-by-import-order.spec.ts, src/utils/__tests__/get-sorted-nodes.spec.ts, src/utils/__tests__/merge-nodes-with-matching-flavors.spec.ts, src/utils/__tests__/remove-nodes-from-original-code.spec.ts, src/utils/adjust-comments-on-sorted-nodes.ts, src/utils/get-code-from-ast.ts, src/utils/get-import-nodes.ts, src/utils/get-sorted-nodes-by-import-order.ts, src/utils/get-sorted-nodes.ts, types/index.d.ts
Reference #22 
This removes the `importOrderCaseInsensitive` option, making sorts always case-insensitive.
=> [Breaking] Remove importOrderCaseInsensitive option

README.md, docs/MIGRATION.md, prettier.config.js, src/index.ts, src/preprocessors/preprocessor.ts, src/types.ts, src/utils/__tests__/get-all-comments-from-nodes.spec.ts, src/utils/__tests__/get-code-from-ast.spec.ts, src/utils/__tests__/get-sorted-nodes-by-import-order.spec.ts, src/utils/__tests__/get-sorted-nodes.spec.ts, src/utils/__tests__/merge-nodes-with-matching-flavors.spec.ts, src/utils/__tests__/remove-nodes-from-original-code.spec.ts, src/utils/get-sorted-nodes-by-import-order.ts, tests/IgnoreComments/__snapshots__/ppsi.spec.ts.snap, tests/TypesSpecialWord/__snapshots__/ppsi.spec.ts.snap, tests/Typescript/__snapshots__/ppsi.spec.ts.snap, types/index.d.ts
Ref #22 
This removes the `importOrderGroupNamespaceSpecifiers`, and always sort the specifiers (i.e. the option is always turned on).  
I removed a few tests as well that are no longer useful due to removed options.
=> [Breaking] Remove importOrderGroupNamespaceSpecifiers option

README.md, src/index.ts, src/preprocessors/preprocessor.ts, src/types.ts, src/utils/__tests__/get-all-comments-from-nodes.spec.ts, src/utils/__tests__/get-code-from-ast.spec.ts, src/utils/__tests__/get-sorted-nodes-by-import-order.spec.ts, src/utils/__tests__/get-sorted-nodes.spec.ts, src/utils/__tests__/merge-nodes-with-matching-flavors.spec.ts, src/utils/__tests__/remove-nodes-from-original-code.spec.ts, src/utils/get-sorted-nodes.ts, tests/Flow/ppsi.spec.ts, tests/TypesSpecialWord/ppsi.spec.ts, tests/Typescript/ppsi.spec.ts, types/index.d.ts
Ref: #22 
This removes the `importOrderMergeDuplicateImports` option.  I can't think of a reason you'd need to have multiple imports from the same module in different statements, and it can cause confusion if you do have them.
=> Remove importOrderMergeDuplicateImports option (always on)

package.json, src/utils/get-sorted-nodes-by-import-order.ts, yarn.lock
I believe the usage of `lodash.clone` used to be more prevalent (and necessary). But at this point we only had 1-remaining call-site, and I traced it, and don't see any mutating methods along the way, so I'm relatively confident this isn't necessary.
I also tested `JSON.parse(JSON.stringify(…))` and that passed the tests too, so if we'd prefer to use that instead, I can do so, just let me know!
=> Clean-up lodash.clone dep, as it serves no purpose

tests/ImportCommentsPreserved/__snapshots__/ppsi.spec.ts.snap, tests/ImportCommentsPreserved/import-comments-directives.ts, tests/ImportCommentsPreserved/import-comments-document-top-test3.ts
Testing that we don't suffer from https://github.com/trivago/prettier-plugin-sort-imports/issues/229 or https://github.com/trivago/prettier-plugin-sort-imports/issues/103 (though I had to add an empty line to make the last one work correctly).
=> Add some more tests for comments

src/utils/get-comment-registry.ts, tests/ImportCommentsPreserved/__snapshots__/ppsi.spec.ts.snap, tests/ImportCommentsPreserved/import-comments-trailing-specifier-comment-lost.ts
Fixes #79
Trailing comments on specifiers don't get automatically saved like top-level ones do.  This ensures that such comments are not lost
Before:
```ts
import {
b2,a2,
// @ts-expect-error
} from "b";
import {
b1,
a1,
// @ts-expect-error
} from "a";
```
After
```ts
import {
a1,
b1,
// @ts-expect-error
} from "a";
import {
a2,
b2,
// @ts-expect-error
} from "b";
```
=> Preserve trailing comments on specifiers

src/utils/__tests__/get-comment-registry.spec.ts, src/utils/adjust-comments-on-sorted-nodes.ts, src/utils/get-all-comments-from-nodes.ts, src/utils/get-comment-registry.ts
I think this makes the code a little easier to follow.
I wasn't able to add an end-to-end integration test around "empty-statements-at-top-of-file" because you're right @IanVS, other layers prevent that from happening.
Instead I added a unit-test to assert the fatal-errors that we throw.
=> Slight reorganization around top-of-file comments

README.md, src/index.ts
Fixes #76 
```js
[
// built-ins are implicitly first
'<THIRD_PARTY_MODULES>', // Actually means "all things that aren't otherwise matched" aka THIRD_PARTY_IMPORTS & Absolute Path Imports
'^[.]', // relative imports
],
```
- There's no way to separate THIRD_PARTY_MODULES and absolute-imports currently
- We can discuss a renaming for THIRD_PARTY_MODULES later
=> Update our Default Sort Order builtins, (thirdparty & absolute paths), relative paths

src/utils/get-comment-registry.ts, tests/ImportCommentsPreserved/__snapshots__/ppsi.spec.ts.snap, tests/ImportCommentsPreserved/import-comments-no-top-gap.ts
This should address https://github.com/IanVS/prettier-plugin-sort-imports/issues/54#issuecomment-1548967488.
Note, we don't currently have a way to _force_ or _remove_ a line at the top, under top-of-file comments, but I think this is okay.  We preserve whatever the user had before, which seems fine.  We can re-evaluate in the future if we hear from users.
=> Prevent comment gap when re-arranging first import

src/preprocessors/vue.ts, tests/Vue/__snapshots__/ppsi.spec.ts.snap, tests/Vue/no-script.vue, tests/Vue/script-and-setup.vue
Fixes https://github.com/trivago/prettier-plugin-sort-imports/issues/218
=> Vue: Sort both script and setup script

README.md, src/constants.ts, src/index.ts, src/utils/get-comment-registry.ts, src/utils/get-import-nodes-matched-group.ts, src/utils/get-sorted-nodes-by-import-order.ts, src/utils/normalize-import-order-options.ts, tests/ImportOrderBuiltinModulesToCustom/__snapshots__/ppsi.spec.ts.snap, tests/ImportOrderBuiltinModulesToCustom/exercise-custom-builtin-modules-spacing.ts, tests/ImportOrderBuiltinModulesToCustom/ppsi.spec.ts, tests/ImportOrderBuiltinModulesToTop/__snapshots__/ppsi.spec.ts.snap, tests/ImportOrderBuiltinModulesToTop/relative-import-with-builtin-substring.ts
- This allows users to specify a gap between built-ins and third-party in a slightly less wonky way, and the plugin's default `importOrder` & related documentation a bit clearer.
- This also allows users to move the built-ins around relative to other imports. (Weakens our previous opinionated decision that built-ins should always be first).
=> Feature: Add `<BUILTIN_MODULES>` Special Word

README.md, src/preprocessors/preprocessor.ts, src/preprocessors/vue.ts, src/utils/get-experimental-parser-plugins.ts, tests/Typescript/__snapshots__/ppsi.spec.ts.snap, tests/Typescript/jsx.tsx, tests/Typescript/old-style-assertion.ts, tests/Typescript/ppsi.spec.ts, tests/Vue/__snapshots__/ppsi.spec.ts.snap, tests/Vue/jsx-in-ts.vue
This fixes a few issues with parser plugins.
It fixes https://github.com/IanVS/prettier-plugin-sort-imports/issues/78 by removing the `jsx` parser plugin when the file is named `.ts` (typescript requires the use of `.tsx` extension for jsx).
It also applies similar logic for .vue files, ensuring that the correct parser plugins are used, with similar logic to the vue compiler itself.
=> Use correct parser plugins for TS and Vue

src/index.ts, tests/Babel-ts/__snapshots__/ppsi.spec.ts.snap, tests/Babel-ts/imports-with-comments.ts, tests/Babel-ts/imports-with-side-effect-imports.ts, tests/Babel-ts/ppsi.spec.ts
Restores compatibility with the latest version of `prettier-plugin-astro`.
Fixes https://github.com/IanVS/prettier-plugin-sort-imports/issues/96.
To confirm, I made this change in the `node_modules` of the project in the above issue, and confirmed that sorting began working correctly again.
=> Support babel-ts parser

src/preprocessors/vue.ts, tests/Vue/__snapshots__/ppsi.spec.ts.snap, tests/Vue/setup.vue
Fixes #100
When replacing a string if the provided replacement is a string it will replace the original string using pattern matching. In the vue preprocessor, the `$` in the code is seen as a regex pattern. Passing a function as a replacement escapes that issue.
=> Fix dollar sign ($) issue in Vue SFC

package.json
(I'm not sure if yarn.lockfile needs to be updated)
fixes #109
=> Add Prettier v3 to Peer dependencies

README.md
Closes https://github.com/IanVS/prettier-plugin-sort-imports/issues/113
This adds a `plugins` config to the example in the `Usage` section of the readme.  It should work correctly in both Prettier 2 and 3, but is now required for 3.
=> Add `plugins` config to README

README.md
Hi there! 
I copy and pasted this from the readme and got confused when I found `react-query` and other `react-` imports also getting sorted to the top. I think it would be a simple change to recommend people use `^react$` instead of just `react` for sorting react to the top. 
Also, thanks so much for this plugin. It's incredible and exactly what I've been looking for!
=> recommend using ^react$ for sorting react to the top.

src/utils/__tests__/explode-type-and-value-specifiers.spec.ts, src/utils/explode-type-and-value-specifiers.ts
Proposed fix for the bug ticket I opened (Fixes https://github.com/IanVS/prettier-plugin-sort-imports/issues/124)
- Prevented type import exploding when no value imports are present
- Added test coverage to cover this edge-case
=> Fix #124 - type import specifier dupe

package.json, yarn.lock
This PR adds [`cross-env`](https://www.npmjs.com/package/cross-env) as `devDependency` to set the `NODE_OPTIONS` env on different OS platforms, fixed the issue Windows Command Prompt and PowerShell cannot recognize that bash syntax used in `test` command.
Closes #133
=> fix: test script on windows

src/preprocessors/vue.ts, tests/Vue/__snapshots__/ppsi.spec.ts.snap, tests/Vue/duplicates-between-blocks.vue
Fix problem mentioned in #90 without changing dependency and shrimpwarp files.
See https://github.com/IanVS/prettier-plugin-sort-imports/pull/90#issuecomment-1758812882 for more details and explanation.
=> fix: vue preprocessor may replace wrong code

package.json, tsconfig.json, yarn.lock
This bumps our devDependencies, and also changes our tsconfig "module" setting to "NodeNext", which is the current recommendation from the TS folks, and allows us to resolve types that are specified in `package.json` "exports" fields.
=> Upgrade development dependencies

src/preprocessors/preprocessor.ts, src/utils/get-code-from-ast.ts, src/utils/get-comment-registry.ts, src/utils/get-import-nodes.ts, yarn.lock
(Note: this is a PR on top of https://github.com/IanVS/prettier-plugin-sort-imports/pull/128)
Lockfiles are great for keeping unexpected changes in dependencies from breaking your app all of a sudden, but they also tend to cause stagnation and duplicated packages (because packages that are added over time use different versions of sub-dependencies). For that reason, it's good to periodically trash the lockfile and re-generate it fresh, which is what this PR does.
I had to tweak some code to make types happy, but our tests are still passing so I think we're still all good.
=> Regenerate lockfile

src/constants.ts, tests/BuiltinModulesNodeTest/__snapshots__/ppsi.spec.ts.snap, tests/BuiltinModulesNodeTest/groups-node-test-with-builtin-modules.js, tests/BuiltinModulesNodeTest/ppsi.spec.ts
Following discussion in #142 , this adds an explicit check for `"node:test"` to `BUILTIN_MODULES_REGEX_STR` in order to properly group it with other builtin modules.
Test covers:
- `"node:test"` correctly gets grouped in with other builtin node modules
- `"node:test"` is correctly sorted among other builtin node modules
- `"*node:test"` is NOT grouped in with builtin modules
- `"node:test*"` is NOT grouped in with builtin modules
- `"node"` is NOT grouped in with builtin modules
- `"test"` is NOT grouped in with builtin modules
Fixes https://github.com/IanVS/prettier-plugin-sort-imports/issues/142
=> Fix: `node:test` not grouped with `<BUILTIN_MODULES>`

package.json, src/utils/get-code-from-ast.ts, yarn.lock
This updates babel in our `dependencies` to be sure that folks are getting the most up-to-date version that supports new syntax like `using` (closes https://github.com/IanVS/prettier-plugin-sort-imports/pull/153).
I also re-generated our `yarn.lock` because I was getting some type errors, and removed `sourceFile` in one spot because it's no longer needed and throws a TypeScript error.
=> Update Babel to 7.24

package.json, src/preprocessors/vue.ts
Pulls in https://github.com/trivago/prettier-plugin-sort-imports/pull/215 from upstream, to add support for Vue 2.7, which as far as I can tell still has ~1 million weekly downloads.
=> Support vue 2.7

README.md, src/constants.ts, src/index.ts, src/preprocessors/preprocessor.ts, src/utils/__tests__/get-all-comments-from-nodes.spec.ts, src/utils/__tests__/get-code-from-ast.spec.ts, src/utils/__tests__/get-sorted-nodes.spec.ts, src/utils/__tests__/normalize-plugin-options.spec.ts, src/utils/__tests__/remove-nodes-from-original-code.spec.ts, src/utils/normalize-plugin-options.ts, tests/Disabled/__snapshots__/ppsi.spec.ts.snap, tests/Disabled/mess.ts, tests/Disabled/ppsi.spec.ts, types/index.d.ts
Closes https://github.com/IanVS/prettier-plugin-sort-imports/issues/159
This changes up how we handle `importOrder: []` in the prettier config.  Previously, we would have applied our default config, such that builtins, node modules, and relative imports would be sorted.  Now, it effectively disables the plugin so that no sorting takes place.
This could be seen as a breaking change, but instead I see it as a bug fix.  It doesn't make sense that using an explicit empty array for the setting causes a fallback to be used.  
Additionally, this gives users more control over disabling the plugin and turning it on only for certain subfolders or types of files, as shown in the referenced issue and documented in the readme in this PR.
=> Allow disabling plugin by setting importOrder to `[]`

package.json, src/preprocessors/vue.ts, yarn.lock
Fixes https://github.com/IanVS/prettier-plugin-sort-imports/issues/158
The `transformRef` method is not found on the most recent versions of @vue/compiler-sfc (3.4.x), because it seems to have only existed for some versions of 3.x (including the version we use in devDependencies, which is why our tests passed).  I couldn't find any mention of it in the Vue changelog, though it seems like it should have been a breaking change to remove the method.
So, now instead of relying on the presence of a method, we'll import the package.json directly, look at the version field, and make our decision based on that, which should be much safer.
=> Detect vue 2.7 / 3 more reliably

README.md, types/index.d.ts
- Add TypeScript module augmentation for the `prettier` module in `types/index.d.ts` to add the `PluginConfig` interface to the `Options` interface to support proper typing of plugin options in IDEs and during type-checking
- Closes #169
- Compiles and passes tests
=> fix: augment Prettier `Options` types with internal `PluginConfig`

src/utils/__tests__/get-code-from-ast.spec.ts, src/utils/get-code-from-ast.ts, tests/Babel/__snapshots__/ppsi.spec.ts.snap, tests/Babel/imports-with-assertions.ts, tests/Babel/ppsi.spec.ts, tests/Typescript/__snapshots__/ppsi.spec.ts.snap, tests/Typescript/imports-with-assertions.ts, tests/Typescript/ppsi.spec.ts
There are three styles of import assertions/attributes that have been proposed over the years and made it to various stages of TC-39.  Here's a bit of [history](https://github.com/tc39/proposal-import-attributes#history): 
1) `import x from 'x' with type: "json"` - original proposal, made it to stage 2
2) `import x from 'x' assert { type: 'json' };` - import "assertion", got to stage 3, then found problems
3) `import x from 'x' with { type: 'json' };` - import "attribute", current proposal, stage 3
Babel only supports these with the use of a parser plugin, either `importAttributes` or `importAssertions`.  Also, babel/generator has to be told which style to generate.  Upstream has a PR, https://github.com/trivago/prettier-plugin-sort-imports/pull/273/files, which adds another user-level …
=> Add support for import attributes

src/preprocessors/vue.ts
Fixes https://github.com/IanVS/prettier-plugin-sort-imports/issues/162
Older versions (not sure which ones exactly) of vue/compiler-sfc do not include a `loc` property on each block, but rather give the offsets directly on the block itself.  This accounts for those differences, and causes the reproduction provided in the issue to succeed.
=> Fix vue 2.7 support

README.md, docs/TROUBLESHOOTING.md, package.json, src/preprocessors/preprocessor.ts, test-setup/run_spec.ts, tests/Astro/__snapshots__/ppsi.spec.ts.snap, tests/Astro/ppsi.spec.ts, tests/Astro/return-outside-function.astro, yarn.lock
Addresses https://github.com/IanVS/prettier-plugin-sort-imports/issues/96#issuecomment-2198005393
In Astro, it's possible to [return a Response](https://docs.astro.build/en/guides/server-side-rendering/#return-a-response-object) from inside of a component script, without wrapping it in a function.  This doesn't look like valid JavaScript, so the babel parser choked on it.  
This change checks to see if the file was parsed with the astro plugin, and if so, enables the `allowReturnOutsideFunction` parser option.  
This is admittedly a bit of a band-aid.  I think the more correct approach is to parse the code into AST using the configured parser, rather than always using our version of babel.  This is what some other prettier plugins do.  Some, like tailwindcss, goes so far as to load a list …
=> Add support for return in Astro component script

README.md, src/index.ts, src/natural-sort/__tests__/natural-sort.spec.ts, src/natural-sort/index.ts, src/types.ts, src/utils/__tests__/get-sorted-import-specifiers.spec.ts, src/utils/__tests__/get-sorted-nodes-by-import-order.spec.ts, src/utils/__tests__/merge-nodes-with-matching-flavors.spec.ts, src/utils/__tests__/normalize-plugin-options.spec.ts, src/utils/get-sorted-import-specifiers.ts, src/utils/get-sorted-nodes-by-import-order.ts, src/utils/get-sorted-nodes-group.ts, src/utils/normalize-plugin-options.ts, tests/ImportOrderCaseSensitive/__snapshots__/ppsi.spec.ts.snap, tests/ImportOrderCaseSensitive/mixed-case.ts, tests/ImportOrderCaseSensitive/ppsi.spec.ts, types/index.d.ts
Implements a custom natural sort algorithm which allows for numeric natural sorting while also sorting all uppercase letters before all lowercase letters, which is the desired behavior here.
For example, when `importOrderCaseSensitive` is false (the default):
```js
import ExampleComponent from './ExampleComponent';
import ExamplesList from './ExamplesList';
import ExampleWidget from './ExampleWidget';
```
Compared with `"importOrderCaseSensitive": true`:
```js
import ExampleComponent from './ExampleComponent';
import ExampleWidget from './ExampleWidget';
import ExamplesList from './ExamplesList';
```
Closes #151
=> Re-add `importOrderCaseSensitive` option for case-sensitive sorting

src/utils/get-sorted-nodes-by-import-order.ts, test-setup/run_spec.ts, tests/ImportOrderMissing/importOrderMissing.ts, tests/ImportOrderMissing/ppsi.spec.ts
Closes #190 
This adds a more understandable error message when we encounter an import that does not fit into any group within `sortOrder`.  I think the only time that should happen is when the user adds groups with `<TYPES>^.....` but no fallback `<TYPES>` bucket.  We could try to shove one in somewhere automatically like we do with `<THIRD_PARTY_MODULES>`, but that could be pretty confusing and I don't know where it should go in that case.  This also includes a hint about how to fix the error.
=> Throw an error when no matching sortOrder group

src/preprocessors/preprocessor.ts
This change updates the plugin to catch babel parsing errors, so that we can give prettier a chance to throw.  We're still writing an error to console, so that in the event that prettier doesn't end up throwing, we're still indicating that the import sorting failed.
Closes #197
=> fix: catch babel parse errors

package.json
I've been using the v4 alphas of prettier for a *very long time*, and they have always worked just fine with this plugin.
=> Update peerDeps to allow prettier v4.

.github/ISSUE_TEMPLATE/bug_report.md, CHANGELOG.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, package.json, pnpm-lock.yaml, prettier.config.mjs
Updates the version in our development dependencies to 4.0.0-alpha.12, which runs more quickly than the 3.x version (see https://prettier.io/blog/2023/11/30/cli-deep-dive).
As an added bonus, prettier is now working again in vscode when I work on the project (I think we had a bad config previously).
=> [Internal] Update prettier dev dependency to 4.0 alpha

src/preprocessors/preprocessor.ts, tests/InvalidSyntax/__snapshots__/ppsi.spec.ts.snap, tests/InvalidSyntax/invalidSet.ts, tests/InvalidSyntax/ppsi.spec.ts, tests/InvalidSyntax/redeclare.js, tests/InvalidSyntax/returnOutsideFunction.ts, tests/InvalidSyntax/superOutsideMethod.ts
Closes #219
Closes #222 
This change makes our babel parsing and node traversal more tolerant of errors, matching the settings and behavior of Prettier itself.  Now, rather than this plugin causing an error and failing to format the file, it will continue to attempt to sort imports.  It may still fail on invalid code, but in those cases prettier itself would as well, so we shouldn't end up in a case where prettier runs but imports aren't sorted, or where prettier would have run as long as this plugin wasn't being used.
I chose not to emit a warning when invalid syntax is encountered, again matching the behavior or prettier.  I don't think it's the responsibility of a import sorting plugin to alert the user to invalid syntax, since it may be intentional and handled later-on in their build …
=> Be more tolerant of babel parse errors

src/preprocessors/preprocessor.ts
Closes #222 
This will stop throwing error messages for un-parsable code blocks in markdown (and mdx) files.  
This isn't ideal, but it matches the behavior of Prettier itself. See https://github.com/IanVS/prettier-plugin-sort-imports/issues/222#issuecomment-3167848337 for some discussion.
=> Do not warn for markdown code blocks
